baseURL       = "../"
languageCode  = "en-uk"
title         = "Saans Psychotherapy"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = "./"
    weight  = 1
  [[menu.nav]]
    name    = "About Me"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "The Process"
    url     = "process"
    weight  = 3
  [[menu.nav]]
    name    = "Sessions & Fees"
    url     = "pricing"
    weight  = 4
  [[menu.nav]]
    name    = "Resources"
    url     = "resources"
    weight  = 5
  [[menu.nav]]
    name    = "Get in touch"
    url     = "#contact"
    weight  = 6

# Site Params
[params]
  logo = "images/logo.webp"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.webp"
    logo_image            = "images/logo.webp"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "WELCOME TO SAANS PYSCHOTHERAPY"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      phone   = "+44 7883 786436"
      email   = "letstalk@saans.co.uk"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Me"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Process"
          url  = "process"
        [[params.footer.sitemap.link]]
          name = "Pricing"
          url  = "pricing"
        [[params.footer.sitemap.link]]
          name = "Resources"
          url  = "resources"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "I am a student member of the UPCA (Universities Psychotherapy and Counselling Association), UKCP (UK Council for Psychotherapy) and the SAC (Singapore Association for Counselling). In order to deepen my knowledge, I take part in trainings several times a year and attend weekly supervision. "
